version: '3.8'

services:
    jenkins:
        build: .
        ports:
            - "8080:8080"
            - "50000:50000" 
        volumes:
            - ./jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/sudoers:/etc/sudoers
            - /usr/bin/docker:/usr/bin/docker
    